### ISSUE TITLE
sci-libs/vtk-8.2.0-r1 failed to build 

### ISSUE THREAD

**Issue by hedmo** [waebbl/waebbl-gentoo#224]
sci-libs/vtk-8.2.0-r1 failed to build 

 - build log : [vtk.log](https://github.com/waebbl/waebbl-gentoo/files/4422013/vtk.log)

 - output of emerge --info =mya51 /home/hedmo #  emerge --info =sci-libs/vtk-8.2.0-r1
Portage 2.3.96 (python 3.6.10-final-0, default/linux/amd64/17.1/desktop/plasma, gcc-10.0.1, glibc-2.30-r6, 5.6.0-xanmod1-x86_64 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.6.0-xanmod1-x86_64-x86_64-Intel-R-_Core-TM-_i7-9700_CPU_@_3.00GHz-with-gentoo-2.7
KiB Mem:    32684884 total,  19445640 free
KiB Swap:    2047996 total,   2044412 free
Head commit of repository nvidia-vulkan: 37106b824845209a56221e44c5df1d94ca92ab0c

Timestamp of repository poly-c: Wed, 01 Apr 2020 16:54:55 +0000
Timestamp of repository gentoo: Wed, 01 Apr 2020 06:37:36 +0000
Head commit of repository gentoo: a43c789f352f3e37092af2a0daca128416423700

sh bash 5.0_p16
ld GNU ld (Gentoo 2.34 p1) 2.34.0
distcc 3.3.3 x86_64-pc-linux-gnu [disabled]
ccache version 3.7.9 [enabled]
app-shells/bash:          5.0_p16::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.1::gentoo
dev-lang/python:          2.7.17-r1::gentoo, 3.6.10-r1::lto-overlay, 3.7.7::gentoo, 3.8.2::gentoo
dev-util/ccache:          3.7.9::gentoo
dev-util/cmake:           3.17.0::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.7::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.16.2::gentoo
sys-devel/binutils:       2.34::gentoo
sys-devel/gcc:            10.0.1_pre9999::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.6::gentoo (virtual/os-headers)
sys-libs/glibc:           2.30-r6::gentoo
Repositories:

nvidia-vulkan
    location: /var/db/repos/nvidia-vulkan
    sync-type: git
    sync-uri: https://github.com/kakra/nvidia-vulkan.git
    masters: gentoo

x-hedmo
    location: /var/lib/local/hedmo
    masters: gentoo
    priority: 0

hedmos-overlay
    location: /var/lib/layman/hedmos-overlay
    masters: gentoo
    priority: 50

kde
    location: /var/lib/layman/kde
    masters: gentoo
    priority: 50

lto-overlay
    location: /var/lib/layman/lto-overlay
    masters: gentoo mv
    priority: 50

mv
    location: /var/lib/layman/mv
    masters: gentoo
    priority: 50

poly-c
    location: /var/lib/layman/poly-c
    masters: gentoo
    priority: 50

qt
    location: /var/lib/layman/qt
    masters: gentoo
    priority: 50

raiagent
    location: /var/lib/layman/raiagent
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    masters: gentoo
    priority: 50

waebbl
    location: /var/lib/layman/waebbl
    masters: gentoo raiagent
    priority: 50

x11
    location: /var/lib/layman/x11
    masters: gentoo
    priority: 50

gentoo
    location: /var/db/repos/gentoo
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gentoo.git
    priority: 1000

Installed sets: @llvm, @steam, @telephony
ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake  -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=9 -fuse-linker-plugin  -falign-functions=32 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt /usr/share/sddm/scripts/Xsetup"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=skylake  -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=9 -fuse-linker-plugin  -falign-functions=32 -pipe"
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--jobs 5 --load-average 8"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=skylake  -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=9 -fuse-linker-plugin  -falign-functions=32 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=skylake  -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=9 -fuse-linker-plugin  -falign-functions=32 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j41 -l9"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="/ X a52 aac acl acpi activities alsa amd64 berkdb bluetooth branding bzip2 cairo cdda cdr cli crypt cups dbus declarative dri dts dvd dvdr egl elogind emboss encode exif ffmpeg flac fortran gdbm gif glamor gles gpm gstreamer gtk iconv icu ipv6 joystick jpeg kde kipi kwallet lcms ldap libglvnd libnotify libtirpc mad mng mp3 mp4 mpeg multilib ncurses networkmanager nls nptl ofono-headset ogg opengl openmp pam pango pcre pdf phonon plasma png policykit ppds pulseaudio qml qt4 qt5 readline sdl seccomp semantic-desktop spell split-usr ssl startup-notification svg tcpd tiff truetype udev udisks unicode upower usb vaapi vorbis vulkan wayland widgets wxwidgets x264 xattr xcb xcomposite xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2018" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2 aes avx avx2 f16c fma3 pclmul popcnt sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput synaptics joystick" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-2" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" RUBY_TARGETS="ruby24 ruby25" USERLAND="GNU" VIDEO_CARDS="nvidia intel i965 nouveau" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

mya51 /home/hedmo # 

As mentioned in #223 sci-libs/vtk-8.2.0-r1::waebbl fails to build and using sci-libs/vtk-8.1.0-r4::Gentoo now 

regards

edit: to help a bit here is an error in that long log:
`FAILED: Imaging/Core/CMakeFiles/vtkImagingCore.dir/vtkImageMirrorPad.cxx.o`

**Comment by waebbl** [comment]
The build fails due to a internal gcc segfault:

```
[31mFAILED: [0mImaging/Core/CMakeFiles/vtkImagingCore.dir/vtkImageMirrorPad.cxx.o 
/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++ -DVTK_IN_VTK -DvtkImagingCore_EXPORTS -IImaging/Core -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Imaging/Core -ICommon/Core -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Common/Core -IUtilities/KWIML -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Utilities/KWIML -IUtilities/KWSys -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Utilities/KWSys -IThirdParty/utf8 -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/ThirdParty/utf8 -ICommon/DataModel -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Common/DataModel -ICommon/Math -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Common/Math -ICommon/Misc -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Common/Misc -ICommon/System -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Common/System -ICommon/Transforms -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Common/Transforms -ICommon/ExecutionModel -I/var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Common/ExecutionModel  -D__STDC_CONSTANT_MACROS -D_UNICODE -march=skylake -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -fuse-linker-plugin -falign-functions=32 -pipe -Wl,-O1 -Wl,--as-needed  -fPIC -fvisibility=hidden   -std=c++11 -MD -MT Imaging/Core/CMakeFiles/vtkImagingCore.dir/vtkImageMirrorPad.cxx.o -MF Imaging/Core/CMakeFiles/vtkImagingCore.dir/vtkImageMirrorPad.cxx.o.d -o Imaging/Core/CMakeFiles/vtkImagingCore.dir/vtkImageMirrorPad.cxx.o -c /var/tmp/portage/sci-libs/vtk-8.2.0-r1/work/VTK-8.2.0/Imaging/Core/vtkImageMirrorPad.cxx
during GIMPLE pass: ivopts
../VTK-8.2.0/Imaging/Core/vtkImageMirrorPad.cxx: In function ‘void vtkImageMirrorPadExecute(vtkImageMirrorPad*, vtkImageData*, int*, vtkImageData*, T*, int*, int) [with T = double]’:
../VTK-8.2.0/Imaging/Core/vtkImageMirrorPad.cxx:53:6: internal compiler error: Segmentation fault
   53 | void vtkImageMirrorPadExecute(vtkImageMirrorPad *self,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.gentoo.org/> for instructions.
```
Several things come into my mind:
- temporarily lower your optimization level and try again
- temporarily switch off LTO
- you have some compiler flag, which I haven't seen, but from their names, they could be aggressive optimization flags: -floop-nest-optimize, -fdevirtualize-at-ltrans, -flto=9, maybe others as well. Could you try again without some of them?
- is the bug reproducibable with this error at the same point?

I'm not convinced this is a problem with the ebuild.

**Comment by hedmo** [comment]
@waebbl  I have removed the flags one by one an all fails.Here is a cleaner build.log:

[vtk.log](https://github.com/waebbl/waebbl-gentoo/files/4422814/vtk.log)

regards

**Comment by waebbl** [comment]
That's a completely different error though. I'm going to check whether I can reproduce it.

**Comment by waebbl** [comment]
@hedmo Please try one other thing first. Use an gcc which isn't masked, e.g. gcc:9.3.0. I just want to try and install gcc:10 on my testbox and got a build failure with
```
 * ERROR: sys-devel/gcc-10.0.1_pre9999::gentoo-git failed (pretend phase):
 *   Please `export I_PROMISE_TO_SUPPLY_PATCHES_WITH_BUGS=1` or define it in your make.conf if you want to use this version.
```
which very likely is there, because this version can most likely lead to problems.

**Comment by hedmo** [comment]
> @hedmo Please try one other thing first. Use an gcc which isn't masked, e.g. gcc:9.3.0. I just want to try and install gcc:10 on my testbox and got a build failure with
> 
> ```
>  * ERROR: sys-devel/gcc-10.0.1_pre9999::gentoo-git failed (pretend phase):
>  *   Please `export I_PROMISE_TO_SUPPLY_PATCHES_WITH_BUGS=1` or define it in your make.conf if you want to use this version.
> ```
> 
> which very likely is there, because this version can most likely lead to problems. This overlay isn't a sandbox for testing out unstable gcc versions.

@waebbl i will check with gcc-9.3.0.i understand and know This overlay isn't a sandbox for testing out unstable gcc versions.why i informing you is that i have freecad-9999::waebbl.
`mya51 /home/hedmo # emerge -av freecad

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   *] media-gfx/freecad-9999::waebbl  USE="addonmgr arch drawing fem idf image inspection material mesh openscad part_design path points raytracing robot show spreadsheet surface techdraw tux (-assembly) -debug -doc -mpi (-netgen) -pcl -plot -ship" PYTHON_SINGLE_TARGET="python3_6" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] n

Quitting.

mya51 /home/hedmo # ` =FreeCAD 0.19 Revision: 20306 (Git)
but sci-libs/vtk-8.2.0-r1 is failing and media-gfx/freecad-0.18.4-r1 to.

regards

**Comment by waebbl** [comment]
Thank you! Please understand, I only want to make sure it's related to the ebuild and not to some external sources, which I cannot change. A bug has to be reproducable in some way, which this issue isn't so far. The provided logs both fail with different errors, not even related to each other. 

I have very limited time to work on this repository, and both gcc and vtk are packages which take some time on my machine, especially when I have to compile them several times until a bug is fixed and tested.

**Comment by waebbl** [comment]
> edit: to help a bit here is an error in that long log:
> `FAILED: Imaging/Core/CMakeFiles/vtkImagingCore.dir/vtkImageMirrorPad.cxx.o`
FYI this isn't of much helpf. I don't need any error, but exactly the very first error. All later ones could be follow-ups from the first. That's why I ask for the complete build logs.

**Comment by waebbl** [comment]
I tried reproducing this. First I needed to add a dependency, which will be solved in an update coming after this message.
I was not able to build with `gcc:10` but it built against `gcc:9.3.0` without any issues, so I assume the issue **is** related to `gcc:10`. Can you try again with the upcoming patch?
If the bug still exists with `gcc:9.3.0` you might want to try without ccache, which has been a source of build time issues in the past, but I wanted to ensure none of the other points is related to this first.

**Comment by waebbl** [comment]
This was the error, I got with `gcc:10`:

```
1495/8276] : && /usr/bin/x86_64-pc-linux-gnu-g++  -O2 -pipe -march=bdver2 -mprefer-avx128 -mvzeroupper -frecord-gcc-switches  -Wl,-lc  -Wl,-lc -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 Rendering/OpenGL2/CMakeFiles/vtkProbeOpenGLVersion.dir/vtkProbeOpenGLVersion.cxx.o  -o bin/vtkProbeOpenGLVersion  -Wl,-rpath,/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/vtk-8.2.0_build/lib64  lib64/libvtkRenderingOpenGL2.so.1  lib64/libvtkRenderingCore.so.1  lib64/libvtkFiltersCore.so.1  /usr/lib64/libSM.so  /usr/lib64/libICE.so  /usr/lib64/libX11.so  /usr/lib64/libXext.so  /usr/lib64/libXt.so  lib64/libvtkCommonExecutionModel.so.1  lib64/libvtkCommonDataModel.so.1  lib64/libvtkCommonTransforms.so.1  lib64/libvtkCommonMisc.so.1  lib64/libvtkCommonMath.so.1  lib64/libvtkCommonCore.so.1  -Wl,-rpath-link,/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/vtk-8.2.0_build/lib64 && :
FAILED: bin/vtkProbeOpenGLVersion 
: && /usr/bin/x86_64-pc-linux-gnu-g++  -O2 -pipe -march=bdver2 -mprefer-avx128 -mvzeroupper -frecord-gcc-switches  -Wl,-lc  -Wl,-lc -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 Rendering/OpenGL2/CMakeFiles/vtkProbeOpenGLVersion.dir/vtkProbeOpenGLVersion.cxx.o  -o bin/vtkProbeOpenGLVersion  -Wl,-rpath,/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/vtk-8.2.0_build/lib64  lib64/libvtkRenderingOpenGL2.so.1  lib64/libvtkRenderingCore.so.1  lib64/libvtkFiltersCore.so.1  /usr/lib64/libSM.so  /usr/lib64/libICE.so  /usr/lib64/libX11.so  /usr/lib64/libXext.so  /usr/lib64/libXt.so  lib64/libvtkCommonExecutionModel.so.1  lib64/libvtkCommonDataModel.so.1  lib64/libvtkCommonTransforms.so.1  lib64/libvtkCommonMisc.so.1  lib64/libvtkCommonMath.so.1  lib64/libvtkCommonCore.so.1  -Wl,-rpath-link,/var/tmp/portage/sci-libs/vtk-8.2.0-r2/work/vtk-8.2.0_build/lib64 && :
lib64/libvtkCommonTransforms.so.1: error: undefined reference to 'vtkMath::Identity3x3(float (*) [3])'
lib64/libvtkCommonTransforms.so.1: error: undefined reference to 'vtkMath::Multiply3x3(float const (*) [3], float const (*) [3], float (*) [3])'
```

followed a whole lot of additional undefined references.

**Comment by hedmo** [comment]
@waebbl sorry for a late response. I have been busy catching the sun. sci-libs/vtk-8.2.0-r1  builds with
`gcc:9.3.0` so it is `gcc:10` related.i will try to build sci-libs/vtk-8.2.0-r2 and post back

**Comment by waebbl** [comment]
It should build with `gcc:9.3.0`. The revbump has only an added dependency on `dev-cpp/eigen` which was missing.

**Comment by hedmo** [comment]
@waebbl i have been tying the hole day to give you some good info but i am stuck. sci-libs/vtk-8.2.0-r1 and sci-libs/vtk-8.2.0-r2 works with `gcc:9.3.0` but not with `gcc:10`. sci-libs/vtk8.1.0-r5 from gentoo compiles fine  with `gcc:10`. i am getting the same error as you:  `FAILED: bin/vtkProbeOpenGLVersion ` and think it is a bug in the  vtk-8.2.0 release to build against `gcc:10`.
it would have been nice to see if the  9.0.0.rc1.

**Comment by waebbl** [comment]
I think this is due some changes in gcc:10 which we are not yet aware. Why the 8.1.0 builds, but not the 8.2.0, I don't know. There are many options, the code having changed between the two versions to start with.
I'm sorry, I don't have the time to get into fixing toolchain apps. If you want to give it try, you are welcome to point out any findings you get and I can try to fix this. But with vtk-9.0.0 at the horizon, I will rather focus on that.
Thanks again for testing the new ebuild.

**Comment by hedmo** [comment]
FYI . sci-libs/vtk-9.0.0_rc1 builds fine. And i am going to test sci-libs/vtk-9.0.0_ rc2 to.

**Comment by hedmo** [comment]
vtk-8.2.0 builds with gcc-10.patch and fno-common.patch from gentoo
