### ISSUE TITLE
dev-python/pivy-0.6.4 build error

### ISSUE THREAD

**Issue by brothermechanic** [waebbl/waebbl-gentoo#84]
pivy/coin_wrap.cpp:6342:40: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
http://dpaste.com/1SEK7H8

**Comment by waebbl** [comment]
Hi @brothermechanic, this ebuild is not from my overlay, see maintainer in the build log and also, I don't have python 3.7 support yet in my ebuild. Please consider filing a bug at b.g.o or contact the maintainer from the output.

**Comment by brothermechanic** [comment]
this is your ebuild + python 3.7
i need python 3.7 - this is blender hard dep
please add experimental ebuild with python 3.7
i think your ebuild has this issue anyway

**Comment by waebbl** [comment]
No it's not. My ebuild has
PYTHON_COMPAT=( python3_7 )
and won't compile against python-3.7.
The system isn't ready for python-3.7, else it would already be stabel in the tree. I'm sorry, I can not fix this.
